### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [shifty0g/shiftys-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by shifty0g** [comment]
there you go mate.  do what you like with it . enjoy

**Comment by unixorn** [comment]
What name do you want it entered as? zsh-prompt is pretty generic.

**Comment by unixorn** [comment]
If you rename it, please rename the repo to match - it'll make it easier for people to configure their frameworks to load it if it is username/themename

**Comment by shifty0g** [comment]
done.. not the best with names

**Comment by unixorn** [comment]
Thanks, adding it

**Comment by shifty0g** [comment]
added LICENCE

**Comment by unixorn** [comment]
Thanks!
